// <auto-generated />
namespace MachineLearning.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PokeIdIntAndPokeBody : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PokeIdIntAndPokeBody));
        
        string IMigrationMetadata.Id
        {
            get { return "201311112219599_PokeIdIntAndPokeBody"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
