// <auto-generated />
namespace MachineLearning.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LotOfChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LotOfChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201311121835022_LotOfChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
