// <auto-generated />
namespace MachineLearning.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ExpPokemon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpPokemon));
        
        string IMigrationMetadata.Id
        {
            get { return "201311181616110_ExpPokemon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
